### ISSUE TITLE
laravel 8 not support

### ISSUE THREAD

**Issue by hassan-raza123** [omar-ehab/laravel-aramex#1]
this is not working
![Screenshot (80)](https://user-images.githubusercontent.com/96716200/164618624-d6d2c15d-1bbb-459e-b747-3a1d9e0fd343.png)

**Comment by hassan-raza123** [comment]
answer this problem plz

**Comment by omar-ehab** [comment]
please check the spelling of the composer require command

you are typing 
`composer require OmarEhab/laravel-aramex `

it's

`composer require omar-ehab/laravel-aramex `
